# Generated by Django 6.0.8 on 2026-09-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placesearchlog_place_opening_hours_menuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('food', 'Nhà hàng / Ẩm thực'), ('cafe', 'Quán cà phê'), ('beverage', 'Quán nước / Đồ uống'), ('hotel', 'Khách sạn / Lưu trú'), ('shop', 'Cửa hàng'), ('scenic_spot', 'Danh lam thắng cảnh'), ('historical_site', 'Di tích lịch sử'), ('beach', 'Bãi biển'), ('museum', 'Bảo tàng')], max_length=30),
        ),
    ]
