# Generated by Django 6.0.8 on 2026-09-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Dán link Google Maps của địa điểm (mở app Google Maps, bấm Chia sẻ → Sao chép liên kết).'),
        ),
    ]
