"""
Django settings for forumtourist project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / '.env')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-n=irpmn9)9d)=pn%szznp(6d!cdgz1hvea7px2f=x!z!hav3=7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Auth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Tác vụ nền
    'django_celery_beat',

    # Bảo mật: captcha cho đăng ký / đăng bài diễn đàn
    'captcha',

    # Local apps
    'accounts',
    'places',
    'reviews',
    'lists',
    'forum',
    'gamification',
    'moderation',
    'social',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'forumtourist.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'forumtourist.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Bảo mật: hash mật khẩu bằng Argon2 (ưu tiên), giữ PBKDF2 để verify hash cũ
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]


# Custom user model — accounts.User (AbstractUser + is_business_owner/owned_place)
AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'account_login'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

LOGIN_REDIRECT_URL = '/places/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/places/'

# django-allauth: email/password + Google OAuth only (không Facebook, không OTP SMS)
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True
# Xác thực tài khoản qua link email built-in của allauth (không tự viết OTP số)
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

# Bảo mật: giới hạn số lần đăng nhập/gửi email xác thực sai trong khoảng thời gian
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',
    'signup': '10/m/ip',
    'send_email': '3/m',
}

ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CaptchaSignupForm',
}

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': env('GOOGLE_OAUTH_CLIENT_ID', default=''),
            'secret': env('GOOGLE_OAUTH_CLIENT_SECRET', default=''),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
}


# Cache (dùng cho cache framework + django-ratelimit). Chưa có Redis server thật chạy trên máy dev
# -> mặc định LocMemCache; đặt CACHE_URL=redis://... trong .env khi đã có Redis thật.
CACHES = {
    'default': env.cache('CACHE_URL', default='locmemcache://'),
}


# Celery — tác vụ nền: tự đóng seasonal mission hết hạn, gửi thông báo
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Chưa có Celery worker + Redis broker thật chạy nền -> để True cho task chạy đồng bộ (không cần broker).
# Khi đã deploy worker/beat thật, đặt CELERY_TASK_ALWAYS_EAGER=False trong .env.
CELERY_TASK_ALWAYS_EAGER = env.bool('CELERY_TASK_ALWAYS_EAGER', default=True)
CELERY_TASK_EAGER_PROPAGATES = False

# Check-in xác thực đánh giá: ngưỡng Haversine (mét)
CHECKIN_DISTANCE_THRESHOLD_M = env.int('CHECKIN_DISTANCE_THRESHOLD_M', default=300)

# Email: gửi thông báo (badge, bình luận mới, kết quả xác minh chủ địa điểm) + link xác thực tài khoản của allauth
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='no-reply@forumtourist.local')
EMAIL_HOST = env('EMAIL_HOST', default='localhost')
EMAIL_PORT = env.int('EMAIL_PORT', default=25)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=False)


# Điểm thưởng & cấp bậc thành viên (gamification)
POINTS_PER_REVIEW = 10
POINTS_PER_COMMENT = 2
POINTS_PER_HELPFUL_VOTE_RECEIVED = 5

# Ngưỡng điểm để lên cấp: Người mới -> Reviewer -> Chuyên gia địa phương
MEMBER_TIER_THRESHOLDS = [
    (500, 'Chuyên gia địa phương'),
    (100, 'Reviewer'),
    (0, 'Người mới'),
]
