# Generated by Django 6.0.8 on 2026-09-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('kinh_nghiem_du_lich', 'Kinh nghiệm du lịch'), ('hoi_dap_dich_vu', 'Hỏi đáp dịch vụ'), ('khac', 'Khác')], default='khac', max_length=30),
        ),
    ]
